### ISSUE TITLE
astyle location in file system is wrong

### ISSUE THREAD

**Issue by silverki** [draekko-rand/gedit-code_beautifier#1]
In file [**init**.py#148](https://github.com/draekko-rand/gedit-code_beautifier/blob/master/plugins/code_beautifier/__init__.py#L148) is:

```
command = ["~/.local/share/gedit/plugins/code-beautifier/code_beautifier/astyle --style="+LANGUAGE+" -xC"+ maxwidthval +" -c -s"+tabval]
```

It should be:

```
command = ["~/.local/share/gedit/plugins/code_beautifier/astyle --style="+LANGUAGE+" -xC"+ maxwidthval +" -c -s"+tabval]
```

**Comment by draekko** [comment]
Thanks for letting me know, i've updated and clarified whats supposed to go where.

**Comment by silverki** [comment]
Thanks for a quick fix. The path is still wrong with modified structure it shall be `/code_beautifier/code_beautifier/`but is `/code-beautifier/code_beautifier/`

**Comment by draekko** [comment]
oh, lol, my bad. In the rush to fix it i mistyped it. Should all be correct now.
